# This is a Docker Compose file for setting up TimescaleDB and pgAdmin
# It uses the latest version of TimescaleDB with PostgreSQL 17
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=tesseus2006@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "8080:80"
    depends_on:
      - timescaledb

volumes:
  timescaledb_data: